data:
  historical_csv: "data/historical.csv"
  features_csv:   "data/data_with_features.csv"
  signals_json:   "data/signals.json"

models:
  xgb_model:     "models/xgb_model.json"
  label_classes: "models/label_classes.pkl"

mt5:
  # terminal_path: "C:/Program Files/MetaTrader 5/terminal64.exe"
  login:             25214081
  password:          "h3MqkJ8>O%2G"
  server:            "demo.mt5tickmill.com"
  reconnect_timeout: 10
  symbol:            "XAUUSD"
  timeframe:         "TIMEFRAME_M1"
  bars_to_fetch:     50000 #10080
  contract_size:     100

training:
  test_size:         0.2
  random_state:      42
  rsi_period:        14
  atr_period:        14
  predict_threshold: 0.6
  xgb_params:
    max_depth:      5
    learning_rate:  0.1
    n_estimators:   100
    objective:      "multi:softprob"
    num_class:      3
  xgb_param_grid:
    max_depth:         [3, 5, 7]
    learning_rate:     [0.01, 0.1, 0.2]
    n_estimators:      [50, 100, 200]
    subsample:         [0.7, 1.0]
    colsample_bytree:  [0.7, 1.0]
    reg_alpha:         [0.0, 0.1, 1.0]
    reg_lambda:        [1.0, 5.0]

features:
  ict:
    mss_lookback:       3
    fvg_threshold:      0.5
  smc:
    order_block_size:         10
    liquidity_void_depth:     5
    breaker_block_lookback:   8
  trend_filter:
    h1_ema_period:     50

risk:
  max_risk_pct:         0.05
  sl_multiplier:        2.5
  tp2_multiplier:       8.0
  trailing_multiplier:  1.5
  min_profit_atr:       1.0
  time_stop_mins:       240
  adx:
    window:             14
    min_trend:          20
    sideway:            15
  max_trades_per_day:   20

execution:
  throttle_mins:        1

rounding:
  lot_decimals:         2

dry_run: False
